apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: g-monitoring-app2-deployment
  namespace: g-monitoring-app2-ns
  labels:
    name: g-monitoring-app2-deployment
    app: g-monitoring-app2-app
    project: g-monitoring-project
spec:
  replicas: 2
  selector:
    matchLabels:
      name: g-monitoring-app2-deployment
      app: g-monitoring-app2-app
      project: g-monitoring-project
  template:
    metadata:
      labels:
        name: g-monitoring-app2-deployment
        app: g-monitoring-app2-app
        project: g-monitoring-project
    spec:
      containers:
        - name: main-container
          image: gandhicloud/g-app-store
          imagePullPolicy: Always
          ports:
            - containerPort: 8080